create calcule and operate methods
rida-elbahtouri/CalculatorReact pull request #4
Opened 2020-09-29 09:00 UTC by rida-elbahtouri

### In this branch I:
- Added calculate logic
- operate method to return new value based on the operation selected

2020-09-29 18:56 UTC, bellom requested changes
## Hi @rida-elbahtouri  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-09-29 18:56 UTC, bellom commented on src/Logic/operate.js
> +      return num1.mod(num2).toString();
When it comes to `%` we only need one operand.
example: click `10` then `%` = 0.01

example: `num1 = (num1 *= 0.01).toString();`

2020-09-29 18:56 UTC, bellom commented on src/Logic/calculate.js
> +
let's try to add a case where a user clicks `.` we should return `0.` on the screen.

example: If click `.` I should see `0.`

2020-09-29 20:50 UTC, rida-elbahtouri commented
most calculators when you click on % you need to add the other number to the result like 4000 % 6 should get 240. because 240 present 6% of the 4000.

2020-09-30 14:48 UTC, Torres-ssf approved these changes
### Milestone approved :+1: 
Hi @rida-elbahtouri :hand: 
Great job implementing the requested changes.
You may merge the PR now.

Happy Coding :computer: 
**Sergio Torres**

2020-09-30 15:01 UTC, merged